### ISSUE TITLE
Esquema de la problemática seleccionada ,

### ISSUE THREAD

**Issue by jploperaa** [jploperaa/Calse_principios_de_desarrollo_de_software#3]

**Comment by jploperaa** [comment]
hacer una grafica del flow del proyecto

**Comment by Amartinev1** [comment]
Hola, ya tengo la imagen del esquema, se las envío por Whatsapp.

**Comment by Sebitas514** [comment]
El diagrama puede hacerse con el modelo de "espina de pescado"
