### ISSUE TITLE
Explicacion de la problematica seleccionada (salud y bienestar)

### ISSUE THREAD

**Issue by jploperaa** [jploperaa/Calse_principios_de_desarrollo_de_software#4]

**Comment by jploperaa** [comment]
por lo menos media pagina.

**Comment by Amartinev1** [comment]
Recuerden que el proyecto se basa principalmente en es estrés

**Comment by Sebitas514** [comment]
Deben ser objetivos para no darle complejidad al problema y dar una solución en un campo específico
