### ISSUE TITLE
Idea de solucion

### ISSUE THREAD

**Issue by jploperaa** [jploperaa/Calse_principios_de_desarrollo_de_software#5]

**Comment by jploperaa** [comment]
Pensar en como se puede implementar y que soluciones puede dar este proyecto a quienes y como , hacer una estructura de como funcionaria.

**Comment by Amartinev1** [comment]
Podemos usar el mal balance vida/trabajo como una razón del estrés, lo podriamos orientar tanto a estudiantes como a trabajadores.

**Comment by Sebitas514** [comment]
Implementar una actividad diaria para el usuario, así agregar dinamismo y una mejor recolección de la información
