### ISSUE TITLE
Hacer una lista de funcionalidades del proyecto

### ISSUE THREAD

**Issue by jploperaa** [jploperaa/Calse_principios_de_desarrollo_de_software#6]

**Comment by jploperaa** [comment]
Hacer por lo menos una lista de 20 cosas que demustres las caracteristicas y funcionalidades del proyecto claramente

**Comment by Amartinev1** [comment]
Eso me podría ayudar en el esquema.

**Comment by Sebitas514** [comment]
Primero hay que delimitar que tanto alcance tendrán las funcionalidades
