### ISSUE TITLE
Reglas appa y organizar el trabajo

### ISSUE THREAD

**Issue by jploperaa** [jploperaa/Calse_principios_de_desarrollo_de_software#8]

**Comment by jploperaa** [comment]
revisar ortografia reglas appa y que todo este bien

**Comment by Amartinev1** [comment]
Si las necesitan: Word permite gestionar una base de datos de referencias. Pueden agregar citas en el texto y luego generar una bibliografía.

**Comment by Sebitas514** [comment]
No olviden las márgenes y la justificación del texto, además de la bibliografía
